#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://123.56.129.233/db1
#    username: root
#    password: 824320xh@XH

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://123.56.129.233/db1
      username: root
      password: 824320xh@XH
#配置mybatis
mybatis:
  #映射文件位置
  mapper-locations: classpath:mappers/*Dao.xml
  #配置文件位置
  config-location: classpath:mybatis-config.xml
