server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://123.56.129.233:3306/cloud_order?useSSL=false
    username: root
    password: 824320xh@XH
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: orderService
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        cluster-name: HZ
        namespace: a50ebed9-52be-4c16-9eb1-f638b202c3e9 # 命名空间 dev环境
        ephemeral: false # 是否是临时实例
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
#eureka:
#  client:
#    service-url:
#      defa ultZone: http://127.0.0.1:10086/eureka

userService: # 给某个微服务配置负载均衡规则，这里是userservice服务
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule # 负载均衡规则

# 饥饿加载
ribbon:
  eager-load:
    enabled: true
    clients:
      - userService
